In [2]:
import numpy as np
from scipy.linalg import sqrtm

In [5]:
# Define the CNOT gate (control is qubit 1)
A = np.array(
    [
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
    ],
)

# Define the double (parallel) Hadamards
B = 0.5 * np.array(
    [
        [1., 1., 1., 1.],
        [1., -1., 1., -1.],
        [1., 1., -1., -1.],
        [1., -1., -1., 1.],
    ],
)

# Define the CNOT with qubit 2 as control
C = np.array(
    [
        [1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
    ]
)

# Define the SWAP gate
S = np.array(
    [
        [1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
    ]
)

# Precalculate inverse of these matrices for cleaner code later
B_inv = np.linalg.inv(B)
C_inv = np.linalg.inv(C)

In [4]:
U = np.matmul(S, B_inv)
for mat in [A, B_inv, C]:
    U = np.matmul(mat, U)
U = np.matmul(C_inv, sqrtm(U))

print(f"The final form of U: \n{U}")

The final form of U: 
[[1. +0.j  0. +0.j  0. +0.j  0. +0.j ]
 [0. +0.j  0. +0.j  0. +0.j  1. +0.j ]
 [0. +0.j  0.5-0.5j 0.5+0.5j 0. +0.j ]
 [0. +0.j  0.5+0.5j 0.5-0.5j 0. +0.j ]]


In [13]:
circuit = np.matmul(U, B)
for mat in [C, U, B, A]:
    circuit = np.matmul(mat, circuit)
print(f"Our final circuit with U in it: \n{circuit.round()}")
print(f"Compare to SWAP gate: \n{S}")

Our final circuit with U in it: 
[[1.+0.j 0.+0.j 0.-0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.-0.j]
 [0.-0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.-0.j 0.+0.j 1.+0.j]]
Compare to SWAP gate: 
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
