In [7]:
'''
Get the explicit 2-qubit representation of the matrix U
in the PennyLane Code Camp Challenge problem, described in 
PennyLane video https://www.youtube.com/watch?v=6fM8FatYWt8

Written by Erica Kotta
'''
import numpy as np
from scipy.linalg import sqrtm

In [5]:
'''
Set up the matrices representing the gates we know.
For an explicit example on how to re-derive
these, refer to find_matrix_form_example.pdf.
'''
# Define the CNOT gate (control is qubit 1)
A = np.array(
    [
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
    ],
)

# Define the double (parallel) Hadamards
B = 0.5 * np.array(
    [
        [1., 1., 1., 1.],
        [1., -1., 1., -1.],
        [1., 1., -1., -1.],
        [1., -1., -1., 1.],
    ],
)

# Define the CNOT with qubit 2 as control
C = np.array(
    [
        [1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
    ]
)

# Define the SWAP gate
S = np.array(
    [
        [1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
    ]
)

# Precalculate inverse of these matrices for cleaner code later
B_inv = np.linalg.inv(B)
C_inv = np.linalg.inv(C)

In [21]:
# Apply the operations as written out in README to get final form of U:
U = np.matmul(S, B_inv)
for mat in [A, B_inv, C]:
    U = np.matmul(mat, U)
U = np.matmul(C_inv, sqrtm(U))

print(f"U matrix: \n{U}")

U matrix: 
[[1. +0.j  0. +0.j  0. +0.j  0. +0.j ]
 [0. +0.j  0. +0.j  0. +0.j  1. +0.j ]
 [0. +0.j  0.5-0.5j 0.5+0.5j 0. +0.j ]
 [0. +0.j  0.5+0.5j 0.5-0.5j 0. +0.j ]]


In [23]:
# Check: plug in U to the complete circuit and make sure it matches SWAP gate
circuit = np.matmul(U, B)
for mat in [C, U, B, A]:
    circuit = np.matmul(mat, circuit)
print(f"Final circuit with U: \n{circuit.round()}")
print(f"\nCompare to SWAP gate: \n{S}")

Final circuit with U: 
[[1.+0.j 0.+0.j 0.-0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.-0.j]
 [0.-0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.-0.j 0.+0.j 1.+0.j]]

Compare to SWAP gate: 
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


✌️